Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -27,7 +27,6 @@ jobs:
     env:
       DATABASE_URL: postgresql://test:test@127.0.0.1:5432/mydb
 
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -41,7 +40,7 @@ jobs:
         run: |
           # Check build-time vars
           if [ -z "${{ vars.SERVER_DEPLOY_PATH }}" ]; then echo "❌ Missing secret: SERVER_DEPLOY_PATH"; exit 1; fi
-      
+
           # Check deploy-time secrets
           if [ -z "${{ secrets.SERVER_HOST }}" ]; then echo "❌ Missing secret: SERVER_HOST"; exit 1; fi
           if [ -z "${{ secrets.SERVER_USER }}" ]; then echo "❌ Missing secret: SERVER_USER"; exit 1; fi
@@ -51,14 +50,16 @@ jobs:
           if [ -z "${{ secrets.JWT_SECRET }}" ]; then echo "❌ Missing secret: JWT_SECRET"; exit 1; fi
           if [ -z "${{ secrets.ZDRIVE_KEY }}" ]; then echo "❌ Missing secret: ZDRIVE_KEY"; exit 1; fi
           if [ -z "${{ secrets.ZDRIVE_SECRET }}" ]; then echo "❌ Missing secret: ZDRIVE_SECRET"; exit 1; fi
-          if [ -z "${{ secrets.SMTP_HOST }}" ]; then echo "❌ Missing secret: SMTP_HOST"; exit 1; fi
-          if [ -z "${{ secrets.SMTP_USER }}" ]; then echo "❌ Missing secret: SMTP_USER"; exit 1; fi
+          if [ -z "${{ vars.ZAUTH_KEY }}" ]; then echo "❌ Missing secret: ZAUTH_KEY"; exit 1; fi
+          if [ -z "${{ vars.ZDRIVE_ROOT }}" ]; then echo "❌ Missing secret: ZDRIVE_ROOT"; exit 1; fi
+
+          if [ -z "${{ vars.SMTP_HOST }}" ]; then echo "❌ Missing secret: SMTP_HOST"; exit 1; fi
+          if [ -z "${{ vars.SMTP_USER }}" ]; then echo "❌ Missing secret: SMTP_USER"; exit 1; fi
           if [ -z "${{ secrets.SMTP_PASSWORD }}" ]; then echo "❌ Missing secret: SMTP_PASSWORD"; exit 1; fi
 
           # Check required files
           if [ ! -f "ecosystem.config.js" ]; then echo "❌ Missing file: ecosystem.config.js"; exit 1; fi
-          
-      
+
         shell: bash
 
       - name: Install dependencies
@@ -99,8 +100,8 @@ jobs:
             export DATABASE_URL=${{ secrets.DATABASE_URL }}
             export ZDRIVE_KEY=${{ secrets.ZDRIVE_KEY }}
             export ZDRIVE_SECRET=${{ secrets.ZDRIVE_SECRET }}
-            export SMTP_HOST=${{ secrets.SMTP_HOST }}
-            export SMTP_USER=${{ secrets.SMTP_USER }}
+            export SMTP_HOST=${{ vars.SMTP_HOST }}
+            export SMTP_USER=${{ vars.SMTP_USER }}
             export SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}
             export JWT_SECRET=${{ secrets.JWT_SECRET }}
             npx prisma migrate deploy
